// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RastreadorDeProblemasAPI.Models.dbModels;

namespace RastreadorDeProblemasAPI.Migrations
{
    [DbContext(typeof(RastreadorProblemasContext))]
    [Migration("20210828122947_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.Problema", b =>
                {
                    b.Property<int>("IdProblema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProblema")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdProblemaEstatus")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioAsignado")
                        .HasColumnType("int");

                    b.Property<long>("IdentificadorAlumno")
                        .HasColumnType("bigint");

                    b.HasKey("IdProblema");

                    b.HasIndex("IdProblemaEstatus");

                    b.HasIndex("IdUsuarioAsignado");

                    b.ToTable("Problema");
                });

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.ProblemaEstatus", b =>
                {
                    b.Property<int>("IdProblemaEstatus")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProblemaEstatus");

                    b.ToTable("ProblemaEstatus");
                });

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.Problema", b =>
                {
                    b.HasOne("RastreadorDeProblemasAPI.Models.dbModels.ProblemaEstatus", "IdProblemaEstatusNavigation")
                        .WithMany("Problemas")
                        .HasForeignKey("IdProblemaEstatus")
                        .HasConstraintName("FK_Problema_ProblemaEstatus")
                        .IsRequired();

                    b.HasOne("RastreadorDeProblemasAPI.Models.dbModels.Usuario", "IdUsuarioAsignadoNavigation")
                        .WithMany("Problemas")
                        .HasForeignKey("IdUsuarioAsignado")
                        .HasConstraintName("FK_Problema_Usuario")
                        .IsRequired();

                    b.Navigation("IdProblemaEstatusNavigation");

                    b.Navigation("IdUsuarioAsignadoNavigation");
                });

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.ProblemaEstatus", b =>
                {
                    b.Navigation("Problemas");
                });

            modelBuilder.Entity("RastreadorDeProblemasAPI.Models.dbModels.Usuario", b =>
                {
                    b.Navigation("Problemas");
                });
#pragma warning restore 612, 618
        }
    }
}
